### ISSUE TITLE
Переделка компонента Подписка по fsd 

### ISSUE THREAD

**Issue by aimenin** [Studio-Yandex-Practicum/maxboom_frontend#147]
- [x] Переделать компонент подписка по fsd
- [x] Переделать интерфейс компонента с учетом того, что мы можем получить с бекенда
- [x] Переделать моки с учетом схемы с бекенда

**Comment by vvkon13** [comment]
Переделать компонент подписка по fsd предложение:
1. Компонент Subscribe - Widgets
2. Компонент SubscribeForm - Features

**Comment by ArturKhelshtein** [comment]
> Переделать компонент подписка по fsd предложение:
> 
> 1. Компонент Subscribe - Widgets
> 2. Компонент SubscribeForm - Features

в #160 issues я перенес SubscribeForm в entities, сейчас смотрю на памятку по FSD и наверно соглашусь, что надо перенести в Features
