### ISSUE TITLE
Переделка компонента footer по fsd

### ISSUE THREAD

**Issue by aimenin** [Studio-Yandex-Practicum/maxboom_frontend#160]
- [x] Переделать компонент footer по fsd
- [x] Переделать интерфейс компонента с учетом того, что мы можем получить с бекенда
- [x] Переделать моки с учетом схемы с бекенда

**Comment by ArturKhelshtein** [comment]
@aimenin прошу пояснить 
- что мы можем получить с бэкенда, и как это посмотреть
- как переделать моки?  

по моему в футере статичные данные, т.е. нет данных из мок и из бэка
